name: echo on pull request opend

on:
  pull_request:
    types: opened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    - name: cat
      run: |
        if [ `cat $GITHUB_EVENT_PATH | jq ".pull_request.labels[]" -r | wc -l` -gt 0 ]; then
          COMMENT_URL=`cat $GITHUB_EVENT_PATH | jq ".pull_request.comments_url" -r`
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\": \"No label\"}" $COMMENT_URL
        fi
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
